/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.itson.missgabysshopping.iu;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import controlador.DAO.ClientModel;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.missgabysshopping.entidades.Client;

/**
 *
 * @author Aletz
 */
public class ClientsJP extends javax.swing.JPanel {

    List<Client> clients = new ArrayList();
    int row = -1;
    Client client = new Client();

    /**
     * Creates new form ProductoJP
     */
    public ClientsJP() {
        initComponents();
        clients =ClientModel.getAll("");
        updateTable();
    }

    /**
     * Fills the tblClients table
     */
    public void updateTable() {
        DefaultTableModel model = (DefaultTableModel) tblClients.getModel();
        model.setNumRows(0);
        int nList = 0;
        for (Client c : clients) {
            nList++;
            model.addRow(new Object[]{
                c.getId(), c.getName(), c.getAddress(), c.getEmail(), c.getPhone(), c.getContact(), c.getRfc(), c.isRemoved()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelBuscar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClients = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnEliminarP = new javax.swing.JButton();
        jPanelActualizar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txfNameEdit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txfAddressEdit = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txfEmailEdit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txfPhoneEdit = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txfContactEdit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txfRfcEdit = new javax.swing.JTextField();
        btnActualizarP = new javax.swing.JButton();
        jPanelIntroducir = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txfPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txfContact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txfRfc = new javax.swing.JTextField();
        btnIngresarP = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1442, 559));

        jLabel10.setText("Buscar cliente");

        tblClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Direccion", "Correo", "Telefono", "Contacto", "Rfc"
            }
        ));
        tblClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClients);

        btnBuscar.setText("Buscar por nombre");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminarP.setText("Eliminar");
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                .addGap(0, 298, Short.MAX_VALUE)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(377, 377, 377))))
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminarP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
        );

        jLabel11.setText("Actualizar Cliente");

        jLabel12.setText("Nombre");

        jLabel13.setText("Direcciom");

        jLabel14.setText("Correo");

        jLabel15.setText("Telefono");

        jLabel16.setText("Contacto");

        jLabel17.setText("Rfc");

        btnActualizarP.setText("Actualizar");
        btnActualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelActualizarLayout = new javax.swing.GroupLayout(jPanelActualizar);
        jPanelActualizar.setLayout(jPanelActualizarLayout);
        jPanelActualizarLayout.setHorizontalGroup(
            jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActualizarLayout.createSequentialGroup()
                .addGroup(jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActualizarLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel11))
                    .addGroup(jPanelActualizarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelActualizarLayout.createSequentialGroup()
                                .addGroup(jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfNameEdit)
                                    .addComponent(txfAddressEdit)
                                    .addComponent(txfEmailEdit)
                                    .addComponent(txfPhoneEdit)
                                    .addComponent(txfContactEdit)
                                    .addComponent(txfRfcEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActualizarLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnActualizarP)
                                .addGap(46, 46, 46)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanelActualizarLayout.setVerticalGroup(
            jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfAddressEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPhoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txfContactEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txfRfcEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnActualizarP)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jLabel2.setText("ingresar cliente");

        jLabel3.setText("Nombre");

        jLabel4.setText("Direccion");

        jLabel5.setText("Correo");

        jLabel6.setText("telefono");

        jLabel7.setText("Contacto");

        jLabel8.setText("rfc");

        btnIngresarP.setText("Ingresar");
        btnIngresarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIntroducirLayout = new javax.swing.GroupLayout(jPanelIntroducir);
        jPanelIntroducir.setLayout(jPanelIntroducirLayout);
        jPanelIntroducirLayout.setHorizontalGroup(
            jPanelIntroducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIntroducirLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIntroducirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelIntroducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIntroducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresarP, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelIntroducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txfName, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(txfAddress)
                        .addComponent(txfEmail)
                        .addComponent(txfPhone)
                        .addComponent(txfContact)
                        .addComponent(txfRfc)))
                .addGap(84, 84, 84))
        );
        jPanelIntroducirLayout.setVerticalGroup(
            jPanelIntroducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIntroducirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelIntroducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIntroducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIntroducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIntroducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIntroducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txfContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIntroducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txfRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnIngresarP)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        btnReport.setText("Generar Reporte");
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanelIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jPanelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(btnReport))
                    .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnReport)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnIngresarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPActionPerformed

        String name = txfName.getText();
        String address = txfAddress.getText();
        String email = txfEmail.getText();
        String phone = txfEmail.getText();
        String contact = txfPhone.getText();
        String rfc = txfContact.getText();

        String nameEmpty = name.replaceAll(" ", "");
        String addressEmpty = address.replaceAll(" ", "");
        String emailEmpty = email.replaceAll(" ", "");
        String phoneEmpty = phone.replaceAll(" ", "");
        String contactEmpty = contact.replaceAll(" ", "");
        String rfcEmpty = rfc.replaceAll(" ", "");

        if (!(nameEmpty.length() == 0 || addressEmpty.length() == 0 || emailEmpty.length() == 0 || phoneEmpty.length() == 0 || contactEmpty.length() == 0 || rfcEmpty.length() == 0)) {
            if (ClientModel.save(name, address, email, phone, contact, rfc)) {
                txfName.setText("");
                txfAddress.setText("");
                txfEmail.setText("");
                txfEmail.setText("");
                txfPhone.setText("");
                txfContact.setText("");
                JOptionPane.showMessageDialog(this, "Se ha añadido el cliente exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Favor de llenar todos los campos");
            }
        }

        clients = ClientModel.getAll("");
        updateTable();


    }//GEN-LAST:event_btnIngresarPActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        clients = ClientModel.getAll(txfSearch.getText());
        updateTable();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed
        if (row != -1) {
            int id = Integer.parseInt(String.valueOf(tblClients.getValueAt(row, 0)));
            ClientModel.delete(id);
            clients = ClientModel.getAll(txfSearch.getText());
            updateTable();
            row = -1;
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente");
        }

    }//GEN-LAST:event_btnEliminarPActionPerformed

    private void btnActualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPActionPerformed

        if (row != -1) {

            String name = txfNameEdit.getText();
            String address = txfAddressEdit.getText();
            String email = txfEmailEdit.getText();
            String phone = txfPhoneEdit.getText();
            String contact = txfContactEdit.getText();
            String rfc = txfRfcEdit.getText();

            String nameEmpty = name.replaceAll(" ", "");
            String addressEmpty = address.replaceAll(" ", "");
            String emailEmpty = email.replaceAll(" ", "");
            String phoneEmpty = phone.replaceAll(" ", "");
            String contactEmpty = contact.replaceAll(" ", "");
            String rfcEmpty = rfc.replaceAll(" ", "");

            if (!(nameEmpty.length() == 0 || addressEmpty.length() == 0 || emailEmpty.length() == 0 || phoneEmpty.length() == 0 || contactEmpty.length() == 0 || rfcEmpty.length() == 0)) {

                if (ClientModel.Update(client.getId(), name, address, email, phone, contact, rfc, client.isRemoved())) {

                    txfNameEdit.setText("");
                    txfAddressEdit.setText("");
                    txfEmailEdit.setText("");
                    txfPhoneEdit.setText("");
                    txfContactEdit.setText("");
                    txfRfcEdit.setText("");
                    JOptionPane.showMessageDialog(this, "Se ha editado al cliente " + client.getId() + " exitosamente");

                } else {
                    txfNameEdit.setText("");
                    txfAddressEdit.setText("");
                    txfEmailEdit.setText("");
                    txfPhoneEdit.setText("");
                    txfContactEdit.setText("");
                    txfRfcEdit.setText("");
                    JOptionPane.showMessageDialog(this, "No se ha podido editar al cliente");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Favor de llenar todos los campos");
            }

            clients = ClientModel.getAll("");
            updateTable();
            row = -1;

        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente");
        }
    }//GEN-LAST:event_btnActualizarPActionPerformed

    private void tblClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientsMouseClicked
         row = tblClients.rowAtPoint(evt.getPoint());
        int id =Integer.parseInt(String.valueOf(tblClients.getValueAt(row, 0)));

        client =ClientModel.getClient(id);

        txfNameEdit.setText(client.getName());
        txfAddressEdit.setText(client.getAddress());
        txfEmailEdit.setText(client.getEmail());
        txfPhoneEdit.setText(client.getPhone());
        txfContactEdit.setText(client.getContact());
        txfRfcEdit.setText(client.getRfc());
    }//GEN-LAST:event_tblClientsMouseClicked

    private void btnReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseClicked
        // Se crea lista de clientes
        List<Client> clients = new ArrayList<Client>();
        
        // Se guardan datos de la base de datos
        clients =ClientModel.getAll("");
        
        // Se crea un documento
        Document documento = new Document();
        FileOutputStream ficheroPDF;
        try {
            // Se crea el pdf
            ficheroPDF = new FileOutputStream("Reporte de clientes.pdf");
            PdfWriter.getInstance(documento, ficheroPDF);
            documento.open();
            // Se le pone titulo al pdf
            Paragraph titulo = new Paragraph("Reporte de Clientes \n\n", FontFactory.getFont("arial", 22, Font.BOLD, BaseColor.RED));
            documento.add(titulo);
            // Se crea tabla
            PdfPTable tabla = new PdfPTable(6);
            // Se le pone tamaño a las celdas
            float[] columnWidths = {15f, 25f, 30f, 30f, 30f, 40f};
            tabla.setWidths(columnWidths);

            // Se le agrega los datos a la celdas de la tabla
            tabla.addCell("Id");
            tabla.addCell("Nombre   ");
            tabla.addCell("Dirección");
            tabla.addCell("Correo");
            tabla.addCell("Telefono");
            tabla.addCell("RFC");
            for (Client e : clients) {
                tabla.addCell("\n" + e.getId()+ "\n");
                tabla.addCell("\n" + e.getName()+ "\n");
                tabla.addCell("\n" + e.getAddress()+ "\n");
                tabla.addCell("\n" + e.getEmail()+ "\n");
                tabla.addCell("\n" + e.getPhone()+ "\n");
                tabla.addCell("\n" + e.getRfc()+ "\n");
            }
            // Se le agrega la tabla al documento
            documento.add(tabla);

            documento.close();
            
            // Abrir el pdf
            File pdfFile = new File("Reporte de clientes.pdf");
            Desktop.getDesktop().open(pdfFile);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(ProductoJP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(ProductoJP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ProductoJP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReportMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarP;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnIngresarP;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelActualizar;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelIntroducir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClients;
    private javax.swing.JTextField txfAddress;
    private javax.swing.JTextField txfAddressEdit;
    private javax.swing.JTextField txfContact;
    private javax.swing.JTextField txfContactEdit;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfEmailEdit;
    private javax.swing.JTextField txfName;
    private javax.swing.JTextField txfNameEdit;
    private javax.swing.JTextField txfPhone;
    private javax.swing.JTextField txfPhoneEdit;
    private javax.swing.JTextField txfRfc;
    private javax.swing.JTextField txfRfcEdit;
    private javax.swing.JTextField txfSearch;
    // End of variables declaration//GEN-END:variables
}
